[workspace]
name = "rl-mesh-deformation"
version = "0.1.0"
description = "rl project environment"
platforms = ["linux-64", "osx-arm64", "win-64"]
channels = ["conda-forge"]

[dependencies]
python = "3.12.*"

# 1. Base Python & Compilation tools
setuptools = "*"
wheel = "*"
ninja = "*"
pip = "*"


# Other scientific libraries
pandas = ">=2"
numpy = ">=2"
matplotlib = "*"
tqdm = "*"
ipython = "*"
plotly = "*"
trimesh = "*"
uniplot = "*"

pytorch = "*"
torchvision = "*"
scikit-learn = "*"
scikit-image = "*"
hydra-core = "*"
omegaconf = "*"

[pypi-dependencies]

rlmd = { path = ".", editable = true }

einops = "*"
vtk = "*"
manifold3d = "*"
pytest = "*"

# for pytorch3d compilation
portalocker = "*"
iopath = "*"

[tasks]
pytorch3d-install = { cmd = "pip install --no-build-isolation git+https://github.com/facebookresearch/pytorch3d.git@v0.7.9", env = { MAX_JOBS = "4" } }
