[workspace]
name = "rl-mesh-deformation"
version = "0.1.0"
description = "rl project environment"
platforms = ["linux-64", "osx-arm64", "win-64"]
channels = ["conda-forge"]

[dependencies]
python = "3.12.*"

# 1. Base Python & Compilation tools
setuptools = "*"
wheel = "*"
ninja = "*"
pip = "*"


# Other scientific libraries
pandas = ">=2"
numpy = ">=2"
matplotlib = "*"
tqdm = "*"
ipython = "*"
plotly = "*"
trimesh = "*"
uniplot = "*"
scikit-learn = "*"
scikit-image = "*"
hydra-core = "*"
omegaconf = "*"

jupyter = "*"

[pypi-dependencies]

rlmd = { path = ".", editable = true }

einops = "*"
vtk = "*"
manifold3d = "*"
pytest = "*"

# for pytorch3d compilation
portalocker = "*"
iopath = "*"

# Lift pytorch into its own feature to separate CPU/GPU
[feature.cpu-only.dependencies]
pytorch = "==2.10.0"
torchvision = "*"

### CUDA supporting extended environment for linux-64
### use with: pixi shell -e cuda, pixi run -e cuda etc.

[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12.8" }
channels = ["nvidia", "conda-forge"]

[feature.cuda.dependencies]
cuda-toolkit = "12.8.*"
cuda-libraries-dev = "12.8.*"
gcc = "13.*"
gxx = "13.*"

[feature.cuda.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]
index-strategy = "unsafe-best-match"

[feature.cuda.pypi-dependencies]
torch = "==2.10.0"
torchvision = "*"

[feature.cuda.activation]
env = { LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH" }

[environments]
default = ["cpu-only"]
cuda = ["cuda"]

[tasks]
pytorch3d-install = { cmd = "pip install --no-build-isolation git+https://github.com/facebookresearch/pytorch3d.git@v0.7.9", env = { MAX_JOBS = "4" } }

