name: triangle_centered_set
dataset:
  _target_: rlmd.dataset.ShapeDiskDataset
  dataset_folder: ${oc.env:RLMD_DATASET,data_generation/generated_dataset}/triangle_centered_set
  shape_names: ["triangle"]
  cache_size: 8
